name: Create Release
on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: 'Type of release'
        required: true
        default: 'patch'
        options:
          - patch
          - minor
          - major
      deno_version:
        type: string
        description: 'Deno version'
        required: true
        default: 'v1.x'


jobs:
  test:
    uses: ./.github/workflows/deno.yml
    with:
      deno_version: ${{ inputs.deno_version }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  create-release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ inputs.deno_version }}
      - run: |
          git config --global user.email "bot@davidpires.pt"
          git config --global user.name "Release Bot"
      - name: Bump version
        run: deno task ci:bump -- ${{ inputs.type }}
      - name: Publish release to JSR
        run: npx jsr publish
