name: PR Validation

on:
  pull_request:
    branches:
      - master

jobs:
  run-test:
    name: Test using deno
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno test -A --coverage
      - run: deno coverage --lcov --output=./coverage/lcov.info
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            verbose: true
            fail_ci_if_error: true
            handle_no_reports_found: true