name: PR Validation

on:
  pull_request:
    branches:
      - master

jobs:
  run:
    uses: ./.github/workflows/deno.yml
    with:
      publish: false
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}