name: Publish

on:
  push:
    branches:
      - master

jobs:
  test:
    uses: ./.github/workflows/deno.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish