name: Publish

on:
  push:
    branches:
      - master

jobs:
  run:
    uses: ./.github/workflows/deno.yml
    with:
      publish: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}